// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="depolarize_hls_depolarize_hls,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200t-fbg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=3018542,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=4263,HLS_SYN_LUT=4348,HLS_VERSION=2023_2}" *)

module depolarize_hls (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        Ni,
        Nj,
        alpha,
        beta,
        biasmul,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 71'd1;
parameter    ap_ST_fsm_state2 = 71'd2;
parameter    ap_ST_fsm_state3 = 71'd4;
parameter    ap_ST_fsm_state4 = 71'd8;
parameter    ap_ST_fsm_state5 = 71'd16;
parameter    ap_ST_fsm_state6 = 71'd32;
parameter    ap_ST_fsm_state7 = 71'd64;
parameter    ap_ST_fsm_state8 = 71'd128;
parameter    ap_ST_fsm_state9 = 71'd256;
parameter    ap_ST_fsm_state10 = 71'd512;
parameter    ap_ST_fsm_state11 = 71'd1024;
parameter    ap_ST_fsm_state12 = 71'd2048;
parameter    ap_ST_fsm_state13 = 71'd4096;
parameter    ap_ST_fsm_state14 = 71'd8192;
parameter    ap_ST_fsm_state15 = 71'd16384;
parameter    ap_ST_fsm_state16 = 71'd32768;
parameter    ap_ST_fsm_state17 = 71'd65536;
parameter    ap_ST_fsm_state18 = 71'd131072;
parameter    ap_ST_fsm_state19 = 71'd262144;
parameter    ap_ST_fsm_state20 = 71'd524288;
parameter    ap_ST_fsm_state21 = 71'd1048576;
parameter    ap_ST_fsm_state22 = 71'd2097152;
parameter    ap_ST_fsm_state23 = 71'd4194304;
parameter    ap_ST_fsm_state24 = 71'd8388608;
parameter    ap_ST_fsm_state25 = 71'd16777216;
parameter    ap_ST_fsm_state26 = 71'd33554432;
parameter    ap_ST_fsm_state27 = 71'd67108864;
parameter    ap_ST_fsm_state28 = 71'd134217728;
parameter    ap_ST_fsm_state29 = 71'd268435456;
parameter    ap_ST_fsm_state30 = 71'd536870912;
parameter    ap_ST_fsm_state31 = 71'd1073741824;
parameter    ap_ST_fsm_state32 = 71'd2147483648;
parameter    ap_ST_fsm_state33 = 71'd4294967296;
parameter    ap_ST_fsm_state34 = 71'd8589934592;
parameter    ap_ST_fsm_state35 = 71'd17179869184;
parameter    ap_ST_fsm_state36 = 71'd34359738368;
parameter    ap_ST_fsm_state37 = 71'd68719476736;
parameter    ap_ST_fsm_state38 = 71'd137438953472;
parameter    ap_ST_fsm_state39 = 71'd274877906944;
parameter    ap_ST_fsm_state40 = 71'd549755813888;
parameter    ap_ST_fsm_state41 = 71'd1099511627776;
parameter    ap_ST_fsm_state42 = 71'd2199023255552;
parameter    ap_ST_fsm_state43 = 71'd4398046511104;
parameter    ap_ST_fsm_state44 = 71'd8796093022208;
parameter    ap_ST_fsm_state45 = 71'd17592186044416;
parameter    ap_ST_fsm_state46 = 71'd35184372088832;
parameter    ap_ST_fsm_state47 = 71'd70368744177664;
parameter    ap_ST_fsm_state48 = 71'd140737488355328;
parameter    ap_ST_fsm_state49 = 71'd281474976710656;
parameter    ap_ST_fsm_state50 = 71'd562949953421312;
parameter    ap_ST_fsm_state51 = 71'd1125899906842624;
parameter    ap_ST_fsm_state52 = 71'd2251799813685248;
parameter    ap_ST_fsm_state53 = 71'd4503599627370496;
parameter    ap_ST_fsm_state54 = 71'd9007199254740992;
parameter    ap_ST_fsm_state55 = 71'd18014398509481984;
parameter    ap_ST_fsm_state56 = 71'd36028797018963968;
parameter    ap_ST_fsm_state57 = 71'd72057594037927936;
parameter    ap_ST_fsm_state58 = 71'd144115188075855872;
parameter    ap_ST_fsm_state59 = 71'd288230376151711744;
parameter    ap_ST_fsm_state60 = 71'd576460752303423488;
parameter    ap_ST_fsm_state61 = 71'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 71'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 71'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 71'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 71'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 71'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 71'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 71'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 71'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 71'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 71'd1180591620717411303424;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input  [31:0] Ni;
input  [31:0] Nj;
input  [31:0] alpha;
input  [31:0] beta;
input  [31:0] biasmul;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [70:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] d_bwsup;
wire   [63:0] d_Wij;
wire   [63:0] d_Xi;
wire   [63:0] d_Bj;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state2;
reg   [0:0] icmp_ln522_reg_589;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state33;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state64;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state71;
wire  signed [61:0] grp_fu_329_p4;
reg   [61:0] reg_343;
wire    ap_CS_fsm_state44;
wire   [31:0] grp_fu_316_p2;
reg   [31:0] reg_349;
wire    ap_CS_fsm_state48;
wire    ap_CS_fsm_state55;
reg   [63:0] d_Bj_read_reg_522;
reg   [63:0] d_Xi_read_reg_538;
reg   [63:0] d_Wij_read_reg_543;
reg   [63:0] d_bwsup_read_reg_548;
wire   [0:0] icmp_ln522_fu_355_p2;
wire   [30:0] trunc_ln561_fu_361_p1;
reg   [30:0] trunc_ln561_reg_617;
reg   [61:0] trunc_ln2_reg_627;
wire   [0:0] grp_fu_338_p2;
reg   [0:0] cmp2_i3763_reg_633;
wire    ap_CS_fsm_state8;
wire   [30:0] trunc_ln522_fu_385_p1;
reg   [30:0] trunc_ln522_reg_638;
wire    ap_CS_fsm_state10;
wire   [31:0] grp_fu_325_p2;
reg   [31:0] mul_ln485_reg_644;
wire   [31:0] select_ln485_fu_389_p3;
reg   [31:0] select_ln485_reg_649;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state19;
wire   [62:0] grp_fu_320_p2;
reg   [62:0] mul_ln482_reg_669;
wire    ap_CS_fsm_state20;
reg   [61:0] trunc_ln3_reg_674;
wire    ap_CS_fsm_state22;
wire   [30:0] empty_35_fu_422_p3;
reg   [30:0] empty_35_reg_680;
wire   [31:0] zext_ln500_fu_439_p1;
wire  signed [61:0] trunc_ln4_fu_443_p4;
reg   [61:0] trunc_ln4_reg_702;
wire   [30:0] trunc_ln511_fu_468_p1;
reg   [30:0] trunc_ln511_reg_712;
wire    ap_CS_fsm_state41;
reg   [31:0] bwsup_stream_read_reg_721;
wire   [31:0] bitcast_ln535_fu_495_p1;
wire    ap_CS_fsm_state45;
reg   [31:0] Bj_stream_read_reg_731;
wire    ap_CS_fsm_state51;
wire   [31:0] bitcast_ln545_fu_499_p1;
wire    ap_CS_fsm_state52;
wire   [31:0] grp_fu_312_p2;
reg   [31:0] temp_3_reg_744;
wire    ap_CS_fsm_state62;
wire    grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_start;
wire    grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_done;
wire    grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_idle;
wire    grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_ready;
wire    grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWVALID;
wire   [63:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWADDR;
wire   [0:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWID;
wire   [31:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWLEN;
wire   [2:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWSIZE;
wire   [1:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWBURST;
wire   [1:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWLOCK;
wire   [3:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWCACHE;
wire   [2:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWPROT;
wire   [3:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWQOS;
wire   [3:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWREGION;
wire   [0:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWUSER;
wire    grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_WVALID;
wire   [31:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_WDATA;
wire   [3:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_WSTRB;
wire    grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_WLAST;
wire   [0:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_WID;
wire   [0:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_WUSER;
wire    grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARVALID;
wire   [63:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARADDR;
wire   [0:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARID;
wire   [31:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARLEN;
wire   [2:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARSIZE;
wire   [1:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARBURST;
wire   [1:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARLOCK;
wire   [3:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARCACHE;
wire   [2:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARPROT;
wire   [3:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARQOS;
wire   [3:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARREGION;
wire   [0:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARUSER;
wire    grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_RREADY;
wire    grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_BREADY;
wire   [31:0] grp_depolarize_hls_Pipeline_read_bwsup_fu_257_bwsup_stream_din;
wire    grp_depolarize_hls_Pipeline_read_bwsup_fu_257_bwsup_stream_write;
wire    grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_start;
wire    grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_done;
wire    grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_idle;
wire    grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_ready;
wire    grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWVALID;
wire   [63:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWADDR;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWID;
wire   [31:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWLEN;
wire   [2:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWSIZE;
wire   [1:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWBURST;
wire   [1:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWLOCK;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWCACHE;
wire   [2:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWPROT;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWQOS;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWREGION;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWUSER;
wire    grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_WVALID;
wire   [31:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_WDATA;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_WSTRB;
wire    grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_WLAST;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_WID;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_WUSER;
wire    grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARVALID;
wire   [63:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARADDR;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARID;
wire   [31:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARLEN;
wire   [2:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARSIZE;
wire   [1:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARBURST;
wire   [1:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARLOCK;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARCACHE;
wire   [2:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARPROT;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARQOS;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARREGION;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARUSER;
wire    grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_RREADY;
wire    grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_BREADY;
wire   [31:0] grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_Wij_stream_din;
wire    grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_Wij_stream_write;
wire    grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_start;
wire    grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_done;
wire    grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_idle;
wire    grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_ready;
wire    grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWVALID;
wire   [63:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWADDR;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWID;
wire   [31:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWLEN;
wire   [2:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWSIZE;
wire   [1:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWBURST;
wire   [1:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWLOCK;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWCACHE;
wire   [2:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWPROT;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWQOS;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWREGION;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWUSER;
wire    grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_WVALID;
wire   [31:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_WDATA;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_WSTRB;
wire    grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_WLAST;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_WID;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_WUSER;
wire    grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARVALID;
wire   [63:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARADDR;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARID;
wire   [31:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARLEN;
wire   [2:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARSIZE;
wire   [1:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARBURST;
wire   [1:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARLOCK;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARCACHE;
wire   [2:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARPROT;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARQOS;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARREGION;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARUSER;
wire    grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_RREADY;
wire    grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_BREADY;
wire   [31:0] grp_depolarize_hls_Pipeline_read_Xi_fu_275_Xi_stream_din;
wire    grp_depolarize_hls_Pipeline_read_Xi_fu_275_Xi_stream_write;
wire    grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_start;
wire    grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_done;
wire    grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_idle;
wire    grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_ready;
wire    grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWVALID;
wire   [63:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWADDR;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWID;
wire   [31:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWLEN;
wire   [2:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWSIZE;
wire   [1:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWBURST;
wire   [1:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWLOCK;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWCACHE;
wire   [2:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWPROT;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWQOS;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWREGION;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWUSER;
wire    grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_WVALID;
wire   [31:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_WDATA;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_WSTRB;
wire    grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_WLAST;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_WID;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_WUSER;
wire    grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARVALID;
wire   [63:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARADDR;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARID;
wire   [31:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARLEN;
wire   [2:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARSIZE;
wire   [1:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARBURST;
wire   [1:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARLOCK;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARCACHE;
wire   [2:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARPROT;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARQOS;
wire   [3:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARREGION;
wire   [0:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARUSER;
wire    grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_RREADY;
wire    grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_BREADY;
wire   [31:0] grp_depolarize_hls_Pipeline_read_Bj_fu_284_Bj_stream_din;
wire    grp_depolarize_hls_Pipeline_read_Bj_fu_284_Bj_stream_write;
wire    grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_start;
wire    grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_done;
wire    grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_idle;
wire    grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_ready;
wire    grp_depolarize_hls_Pipeline_computeRow_fu_293_Xi_stream_read;
wire    grp_depolarize_hls_Pipeline_computeRow_fu_293_Wij_stream_read;
wire   [31:0] grp_depolarize_hls_Pipeline_computeRow_fu_293_temp_1_out;
wire    grp_depolarize_hls_Pipeline_computeRow_fu_293_temp_1_out_ap_vld;
wire   [31:0] grp_depolarize_hls_Pipeline_computeRow_fu_293_grp_fu_316_p_din0;
wire   [31:0] grp_depolarize_hls_Pipeline_computeRow_fu_293_grp_fu_316_p_din1;
wire    grp_depolarize_hls_Pipeline_computeRow_fu_293_grp_fu_316_p_ce;
wire    grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_start;
wire    grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_done;
wire    grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_idle;
wire    grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_ready;
wire    grp_depolarize_hls_Pipeline_store_bwsup_fu_303_bwsup_stream_out_read;
wire    grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWVALID;
wire   [63:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWADDR;
wire   [0:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWID;
wire   [31:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWLEN;
wire   [2:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWSIZE;
wire   [1:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWBURST;
wire   [1:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWLOCK;
wire   [3:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWCACHE;
wire   [2:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWPROT;
wire   [3:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWQOS;
wire   [3:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWREGION;
wire   [0:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWUSER;
wire    grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_WVALID;
wire   [31:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_WDATA;
wire   [3:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_WSTRB;
wire    grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_WLAST;
wire   [0:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_WID;
wire   [0:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_WUSER;
wire    grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARVALID;
wire   [63:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARADDR;
wire   [0:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARID;
wire   [31:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARLEN;
wire   [2:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARSIZE;
wire   [1:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARBURST;
wire   [1:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARLOCK;
wire   [3:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARCACHE;
wire   [2:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARPROT;
wire   [3:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARQOS;
wire   [3:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARREGION;
wire   [0:0] grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARUSER;
wire    grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_RREADY;
wire    grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_BREADY;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg   [63:0] gmem_AWADDR;
reg   [31:0] gmem_AWLEN;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [31:0] gmem_ARLEN;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire   [8:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem_BREADY;
reg    grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_start_reg;
wire    bwsup_stream_full_n;
reg    bwsup_stream_write;
reg    grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_start_reg;
wire    ap_CS_fsm_state21;
wire    Wij_stream_full_n;
reg    Wij_stream_write;
reg    grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_start_reg;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state32;
wire    Xi_stream_full_n;
reg    Xi_stream_write;
reg    grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_start_reg;
wire    ap_CS_fsm_state42;
wire    Bj_stream_full_n;
reg    Bj_stream_write;
reg    grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_start_reg;
wire    ap_CS_fsm_state49;
wire    ap_CS_fsm_state50;
wire   [31:0] Xi_stream_dout;
wire    Xi_stream_empty_n;
reg    Xi_stream_read;
wire   [31:0] Wij_stream_dout;
wire    Wij_stream_empty_n;
reg    Wij_stream_read;
reg    grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_start_reg;
wire    ap_CS_fsm_state65;
wire    ap_CS_fsm_state66;
wire   [31:0] bwsup_stream_out_dout;
wire    bwsup_stream_out_empty_n;
reg    bwsup_stream_out_read;
wire  signed [63:0] sext_ln522_fu_365_p1;
wire  signed [63:0] sext_ln485_fu_395_p1;
wire  signed [63:0] sext_ln500_fu_429_p1;
wire  signed [63:0] sext_ln511_fu_452_p1;
wire  signed [63:0] sext_ln554_fu_511_p1;
reg    ap_block_state2_io;
reg    ap_block_state33_io;
reg    ap_block_state71;
wire    ap_CS_fsm_state56;
reg   [30:0] i_2_fu_152;
wire   [30:0] add_ln533_fu_484_p2;
wire   [31:0] bwsup_stream_dout;
wire    bwsup_stream_empty_n;
reg    bwsup_stream_read;
wire   [0:0] icmp_ln533_fu_479_p2;
reg    ap_block_state44;
wire   [31:0] Bj_stream_dout;
wire    Bj_stream_empty_n;
reg    Bj_stream_read;
wire   [31:0] bwsup_stream_out_din;
wire    bwsup_stream_out_full_n;
reg    bwsup_stream_out_write;
wire    ap_CS_fsm_state63;
reg   [31:0] grp_fu_316_p0;
reg   [31:0] grp_fu_316_p1;
wire   [30:0] grp_fu_320_p0;
wire   [31:0] grp_fu_320_p1;
wire    ap_CS_fsm_state9;
wire  signed [31:0] grp_fu_338_p0;
wire  signed [31:0] icmp_ln522_fu_355_p0;
wire  signed [31:0] trunc_ln561_fu_361_p0;
wire  signed [31:0] trunc_ln522_fu_385_p0;
wire  signed [31:0] zext_ln482_1_fu_409_p0;
wire  signed [31:0] trunc_ln511_fu_468_p0;
wire   [31:0] i_2_cast_fu_475_p1;
wire  signed [31:0] icmp_ln533_fu_479_p1;
reg    grp_fu_316_ce;
reg   [70:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
reg    ap_ST_fsm_state32_blk;
reg    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
reg    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
reg    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
reg    ap_ST_fsm_state50_blk;
reg    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
reg    ap_ST_fsm_state63_blk;
reg    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
reg    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
reg    ap_ST_fsm_state71_blk;
wire   [62:0] grp_fu_320_p00;
wire   [62:0] grp_fu_320_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 71'd1;
#0 grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_start_reg = 1'b0;
#0 grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_start_reg = 1'b0;
#0 grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_start_reg = 1'b0;
#0 grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_start_reg = 1'b0;
#0 grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_start_reg = 1'b0;
#0 grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_start_reg = 1'b0;
#0 i_2_fu_152 = 31'd0;
end

depolarize_hls_depolarize_hls_Pipeline_read_bwsup grp_depolarize_hls_Pipeline_read_bwsup_fu_257(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_start),
    .ap_done(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_done),
    .ap_idle(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_idle),
    .ap_ready(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_ready),
    .m_axi_gmem_AWVALID(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .bwsup_stream_din(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_bwsup_stream_din),
    .bwsup_stream_full_n(bwsup_stream_full_n),
    .bwsup_stream_write(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_bwsup_stream_write),
    .empty(trunc_ln522_reg_638),
    .sext_ln522(reg_343)
);

depolarize_hls_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_start),
    .ap_done(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_done),
    .ap_idle(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_idle),
    .ap_ready(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_ready),
    .m_axi_gmem_AWVALID(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .Wij_stream_din(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_Wij_stream_din),
    .Wij_stream_full_n(Wij_stream_full_n),
    .Wij_stream_write(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_Wij_stream_write),
    .mul_ln482(mul_ln482_reg_669),
    .sext_ln485(trunc_ln2_reg_627)
);

depolarize_hls_depolarize_hls_Pipeline_read_Xi grp_depolarize_hls_Pipeline_read_Xi_fu_275(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_start),
    .ap_done(grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_done),
    .ap_idle(grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_idle),
    .ap_ready(grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_ready),
    .m_axi_gmem_AWVALID(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .Xi_stream_din(grp_depolarize_hls_Pipeline_read_Xi_fu_275_Xi_stream_din),
    .Xi_stream_full_n(Xi_stream_full_n),
    .Xi_stream_write(grp_depolarize_hls_Pipeline_read_Xi_fu_275_Xi_stream_write),
    .Ni(Ni),
    .sext_ln500(trunc_ln3_reg_674)
);

depolarize_hls_depolarize_hls_Pipeline_read_Bj grp_depolarize_hls_Pipeline_read_Bj_fu_284(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_start),
    .ap_done(grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_done),
    .ap_idle(grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_idle),
    .ap_ready(grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_ready),
    .m_axi_gmem_AWVALID(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .Bj_stream_din(grp_depolarize_hls_Pipeline_read_Bj_fu_284_Bj_stream_din),
    .Bj_stream_full_n(Bj_stream_full_n),
    .Bj_stream_write(grp_depolarize_hls_Pipeline_read_Bj_fu_284_Bj_stream_write),
    .empty(trunc_ln511_reg_712),
    .sext_ln511(trunc_ln4_reg_702)
);

depolarize_hls_depolarize_hls_Pipeline_computeRow grp_depolarize_hls_Pipeline_computeRow_fu_293(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_start),
    .ap_done(grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_done),
    .ap_idle(grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_idle),
    .ap_ready(grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_ready),
    .temp(reg_349),
    .Ni(Ni),
    .Xi_stream_dout(Xi_stream_dout),
    .Xi_stream_empty_n(Xi_stream_empty_n),
    .Xi_stream_read(grp_depolarize_hls_Pipeline_computeRow_fu_293_Xi_stream_read),
    .Wij_stream_dout(Wij_stream_dout),
    .Wij_stream_empty_n(Wij_stream_empty_n),
    .Wij_stream_read(grp_depolarize_hls_Pipeline_computeRow_fu_293_Wij_stream_read),
    .alpha(alpha),
    .temp_1_out(grp_depolarize_hls_Pipeline_computeRow_fu_293_temp_1_out),
    .temp_1_out_ap_vld(grp_depolarize_hls_Pipeline_computeRow_fu_293_temp_1_out_ap_vld),
    .grp_fu_316_p_din0(grp_depolarize_hls_Pipeline_computeRow_fu_293_grp_fu_316_p_din0),
    .grp_fu_316_p_din1(grp_depolarize_hls_Pipeline_computeRow_fu_293_grp_fu_316_p_din1),
    .grp_fu_316_p_dout0(grp_fu_316_p2),
    .grp_fu_316_p_ce(grp_depolarize_hls_Pipeline_computeRow_fu_293_grp_fu_316_p_ce)
);

depolarize_hls_depolarize_hls_Pipeline_store_bwsup grp_depolarize_hls_Pipeline_store_bwsup_fu_303(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_start),
    .ap_done(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_done),
    .ap_idle(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_idle),
    .ap_ready(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_ready),
    .bwsup_stream_out_dout(bwsup_stream_out_dout),
    .bwsup_stream_out_empty_n(bwsup_stream_out_empty_n),
    .bwsup_stream_out_read(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_bwsup_stream_out_read),
    .m_axi_gmem_AWVALID(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(1'b0),
    .m_axi_gmem_ARADDR(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(1'b0),
    .m_axi_gmem_RREADY(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(32'd0),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(9'd0),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .empty(trunc_ln511_reg_712),
    .sext_ln554(reg_343)
);

depolarize_hls_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .d_bwsup(d_bwsup),
    .d_Wij(d_Wij),
    .d_Xi(d_Xi),
    .d_Bj(d_Bj)
);

depolarize_hls_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARLEN(gmem_ARLEN),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_AWADDR),
    .I_AWLEN(gmem_AWLEN),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_WDATA),
    .I_WSTRB(grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_WSTRB),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY)
);

depolarize_hls_fadd_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_7_full_dsp_1_U30(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_depolarize_hls_Pipeline_computeRow_fu_293_temp_1_out),
    .din1(reg_349),
    .ce(1'b1),
    .dout(grp_fu_312_p2)
);

depolarize_hls_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U31(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_316_p0),
    .din1(grp_fu_316_p1),
    .ce(grp_fu_316_ce),
    .dout(grp_fu_316_p2)
);

depolarize_hls_mul_31ns_32ns_63_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 63 ))
mul_31ns_32ns_63_2_1_U32(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_320_p0),
    .din1(grp_fu_320_p1),
    .ce(1'b1),
    .dout(grp_fu_320_p2)
);

depolarize_hls_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U33(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(Nj),
    .din1(Ni),
    .ce(1'b1),
    .dout(grp_fu_325_p2)
);

depolarize_hls_fifo_w32_d2_S Wij_stream_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_Wij_stream_din),
    .if_full_n(Wij_stream_full_n),
    .if_write(Wij_stream_write),
    .if_dout(Wij_stream_dout),
    .if_empty_n(Wij_stream_empty_n),
    .if_read(Wij_stream_read)
);

depolarize_hls_fifo_w32_d2_S Xi_stream_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_depolarize_hls_Pipeline_read_Xi_fu_275_Xi_stream_din),
    .if_full_n(Xi_stream_full_n),
    .if_write(Xi_stream_write),
    .if_dout(Xi_stream_dout),
    .if_empty_n(Xi_stream_empty_n),
    .if_read(Xi_stream_read)
);

depolarize_hls_fifo_w32_d2_S Bj_stream_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_depolarize_hls_Pipeline_read_Bj_fu_284_Bj_stream_din),
    .if_full_n(Bj_stream_full_n),
    .if_write(Bj_stream_write),
    .if_dout(Bj_stream_dout),
    .if_empty_n(Bj_stream_empty_n),
    .if_read(Bj_stream_read)
);

depolarize_hls_fifo_w32_d2_S bwsup_stream_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_depolarize_hls_Pipeline_read_bwsup_fu_257_bwsup_stream_din),
    .if_full_n(bwsup_stream_full_n),
    .if_write(bwsup_stream_write),
    .if_dout(bwsup_stream_dout),
    .if_empty_n(bwsup_stream_empty_n),
    .if_read(bwsup_stream_read)
);

depolarize_hls_fifo_w32_d2_S bwsup_stream_out_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(bwsup_stream_out_din),
    .if_full_n(bwsup_stream_out_full_n),
    .if_write(bwsup_stream_out_write),
    .if_dout(bwsup_stream_out_dout),
    .if_empty_n(bwsup_stream_out_empty_n),
    .if_read(bwsup_stream_out_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state49)) begin
            grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_start_reg <= 1'b1;
        end else if ((grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_ready == 1'b1)) begin
            grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state41)) begin
            grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_start_reg <= 1'b1;
        end else if ((grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_ready == 1'b1)) begin
            grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state20)) begin
            grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_start_reg <= 1'b1;
        end else if ((grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_ready == 1'b1)) begin
            grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state31)) begin
            grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_start_reg <= 1'b1;
        end else if ((grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_ready == 1'b1)) begin
            grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_start_reg <= 1'b1;
        end else if ((grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_ready == 1'b1)) begin
            grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state65)) begin
            grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_start_reg <= 1'b1;
        end else if ((grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_ready == 1'b1)) begin
            grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state33_io) & (1'b1 == ap_CS_fsm_state33) & (icmp_ln522_reg_589 == 1'd1))) begin
        i_2_fu_152 <= 31'd0;
    end else if (((icmp_ln533_fu_479_p2 == 1'd0) & (1'b0 == ap_block_state44) & (1'b1 == ap_CS_fsm_state44))) begin
        i_2_fu_152 <= add_ln533_fu_484_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        Bj_stream_read_reg_731 <= Bj_stream_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        bwsup_stream_read_reg_721 <= bwsup_stream_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cmp2_i3763_reg_633 <= grp_fu_338_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        d_Bj_read_reg_522 <= d_Bj;
        d_Wij_read_reg_543 <= d_Wij;
        d_Xi_read_reg_538 <= d_Xi;
        d_bwsup_read_reg_548 <= d_bwsup;
        icmp_ln522_reg_589 <= icmp_ln522_fu_355_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        empty_35_reg_680 <= empty_35_fu_422_p3;
        trunc_ln3_reg_674 <= {{d_Xi_read_reg_538[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        mul_ln482_reg_669 <= grp_fu_320_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        mul_ln485_reg_644 <= grp_fu_325_p2;
        trunc_ln522_reg_638 <= trunc_ln522_fu_385_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state2))) begin
        reg_343 <= {{d_bwsup_read_reg_548[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state48))) begin
        reg_349 <= grp_fu_316_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        select_ln485_reg_649 <= select_ln485_fu_389_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state62)) begin
        temp_3_reg_744 <= grp_fu_312_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln2_reg_627 <= {{d_Wij_read_reg_543[63:2]}};
        trunc_ln561_reg_617 <= trunc_ln561_fu_361_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        trunc_ln4_reg_702 <= {{d_Bj_read_reg_522[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        trunc_ln511_reg_712 <= trunc_ln511_fu_468_p1;
    end
end

always @ (*) begin
    if (((1'b1 == Bj_stream_empty_n) & (1'b1 == ap_CS_fsm_state51))) begin
        Bj_stream_read = 1'b1;
    end else begin
        Bj_stream_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        Bj_stream_write = grp_depolarize_hls_Pipeline_read_Bj_fu_284_Bj_stream_write;
    end else begin
        Bj_stream_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        Wij_stream_read = grp_depolarize_hls_Pipeline_computeRow_fu_293_Wij_stream_read;
    end else begin
        Wij_stream_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        Wij_stream_write = grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_Wij_stream_write;
    end else begin
        Wij_stream_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        Xi_stream_read = grp_depolarize_hls_Pipeline_computeRow_fu_293_Xi_stream_read;
    end else begin
        Xi_stream_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        Xi_stream_write = grp_depolarize_hls_Pipeline_read_Xi_fu_275_Xi_stream_write;
    end else begin
        Xi_stream_write = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_done == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state2_io)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

always @ (*) begin
    if ((grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_done == 1'b0)) begin
        ap_ST_fsm_state32_blk = 1'b1;
    end else begin
        ap_ST_fsm_state32_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state33_io)) begin
        ap_ST_fsm_state33_blk = 1'b1;
    end else begin
        ap_ST_fsm_state33_blk = 1'b0;
    end
end

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

always @ (*) begin
    if ((grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_done == 1'b0)) begin
        ap_ST_fsm_state42_blk = 1'b1;
    end else begin
        ap_ST_fsm_state42_blk = 1'b0;
    end
end

assign ap_ST_fsm_state43_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state44)) begin
        ap_ST_fsm_state44_blk = 1'b1;
    end else begin
        ap_ST_fsm_state44_blk = 1'b0;
    end
end

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_done == 1'b0)) begin
        ap_ST_fsm_state50_blk = 1'b1;
    end else begin
        ap_ST_fsm_state50_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == Bj_stream_empty_n)) begin
        ap_ST_fsm_state51_blk = 1'b1;
    end else begin
        ap_ST_fsm_state51_blk = 1'b0;
    end
end

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

always @ (*) begin
    if ((bwsup_stream_out_full_n == 1'b0)) begin
        ap_ST_fsm_state63_blk = 1'b1;
    end else begin
        ap_ST_fsm_state63_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_AWREADY == 1'b0)) begin
        ap_ST_fsm_state64_blk = 1'b1;
    end else begin
        ap_ST_fsm_state64_blk = 1'b0;
    end
end

assign ap_ST_fsm_state65_blk = 1'b0;

always @ (*) begin
    if ((grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_done == 1'b0)) begin
        ap_ST_fsm_state66_blk = 1'b1;
    end else begin
        ap_ST_fsm_state66_blk = 1'b0;
    end
end

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state71)) begin
        ap_ST_fsm_state71_blk = 1'b1;
    end else begin
        ap_ST_fsm_state71_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_state71) & (1'b1 == ap_CS_fsm_state71))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state71) & (1'b1 == ap_CS_fsm_state71))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        bwsup_stream_out_read = grp_depolarize_hls_Pipeline_store_bwsup_fu_303_bwsup_stream_out_read;
    end else begin
        bwsup_stream_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((bwsup_stream_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state63))) begin
        bwsup_stream_out_write = 1'b1;
    end else begin
        bwsup_stream_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln533_fu_479_p2 == 1'd0) & (1'b0 == ap_block_state44) & (1'b1 == ap_CS_fsm_state44))) begin
        bwsup_stream_read = 1'b1;
    end else begin
        bwsup_stream_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        bwsup_stream_write = grp_depolarize_hls_Pipeline_read_bwsup_fu_257_bwsup_stream_write;
    end else begin
        bwsup_stream_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state33_io) & (1'b1 == ap_CS_fsm_state33) & (icmp_ln522_reg_589 == 1'd1))) begin
        gmem_ARADDR = sext_ln511_fu_452_p1;
    end else if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
        gmem_ARADDR = sext_ln500_fu_429_p1;
    end else if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        gmem_ARADDR = sext_ln485_fu_395_p1;
    end else if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln522_reg_589 == 1'd1))) begin
        gmem_ARADDR = sext_ln522_fu_365_p1;
    end else if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41))) begin
        gmem_ARADDR = grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31))) begin
        gmem_ARADDR = grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_ARADDR = grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARADDR = grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
        gmem_ARLEN = zext_ln500_fu_439_p1;
    end else if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        gmem_ARLEN = select_ln485_reg_649;
    end else if ((((1'b0 == ap_block_state33_io) & (1'b1 == ap_CS_fsm_state33) & (icmp_ln522_reg_589 == 1'd1)) | ((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln522_reg_589 == 1'd1)))) begin
        gmem_ARLEN = Nj;
    end else if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41))) begin
        gmem_ARLEN = grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31))) begin
        gmem_ARLEN = grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_ARLEN = grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARLEN = grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state33_io) & (1'b1 == ap_CS_fsm_state33) & (icmp_ln522_reg_589 == 1'd1)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state23)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln522_reg_589 == 1'd1)))) begin
        gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41))) begin
        gmem_ARVALID = grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31))) begin
        gmem_ARVALID = grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_ARVALID = grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARVALID = grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state64))) begin
        gmem_AWADDR = sext_ln554_fu_511_p1;
    end else if (((1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state65))) begin
        gmem_AWADDR = grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWADDR;
    end else begin
        gmem_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state64))) begin
        gmem_AWLEN = Nj;
    end else if (((1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state65))) begin
        gmem_AWLEN = grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWLEN;
    end else begin
        gmem_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state64))) begin
        gmem_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state65))) begin
        gmem_AWVALID = grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_AWVALID;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state71) & (1'b1 == ap_CS_fsm_state71) & (icmp_ln522_reg_589 == 1'd1))) begin
        gmem_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state65))) begin
        gmem_BREADY = grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_BREADY;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41))) begin
        gmem_RREADY = grp_depolarize_hls_Pipeline_read_Bj_fu_284_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31))) begin
        gmem_RREADY = grp_depolarize_hls_Pipeline_read_Xi_fu_275_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_RREADY = grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_RREADY = grp_depolarize_hls_Pipeline_read_bwsup_fu_257_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state65))) begin
        gmem_WVALID = grp_depolarize_hls_Pipeline_store_bwsup_fu_303_m_axi_gmem_WVALID;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state33) & (icmp_ln522_reg_589 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln522_reg_589 == 1'd1)))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state64)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state71) & (icmp_ln522_reg_589 == 1'd1))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        grp_fu_316_ce = grp_depolarize_hls_Pipeline_computeRow_fu_293_grp_fu_316_p_ce;
    end else begin
        grp_fu_316_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        grp_fu_316_p0 = grp_depolarize_hls_Pipeline_computeRow_fu_293_grp_fu_316_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state52)) begin
        grp_fu_316_p0 = bitcast_ln545_fu_499_p1;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_316_p0 = bitcast_ln535_fu_495_p1;
    end else begin
        grp_fu_316_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        grp_fu_316_p1 = grp_depolarize_hls_Pipeline_computeRow_fu_293_grp_fu_316_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state52)) begin
        grp_fu_316_p1 = biasmul;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_316_p1 = beta;
    end else begin
        grp_fu_316_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln522_reg_589 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln522_reg_589 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            if (((grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_state33 : begin
            if (((1'b0 == ap_block_state33_io) & (1'b1 == ap_CS_fsm_state33) & (icmp_ln522_reg_589 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state71;
            end else if (((1'b0 == ap_block_state33_io) & (1'b1 == ap_CS_fsm_state33) & (icmp_ln522_reg_589 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            if (((grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state42))) begin
                ap_NS_fsm = ap_ST_fsm_state43;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            if (((icmp_ln533_fu_479_p2 == 1'd1) & (1'b0 == ap_block_state44) & (1'b1 == ap_CS_fsm_state44))) begin
                ap_NS_fsm = ap_ST_fsm_state64;
            end else if (((icmp_ln533_fu_479_p2 == 1'd0) & (1'b0 == ap_block_state44) & (1'b1 == ap_CS_fsm_state44))) begin
                ap_NS_fsm = ap_ST_fsm_state45;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            if (((grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state50))) begin
                ap_NS_fsm = ap_ST_fsm_state51;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state50;
            end
        end
        ap_ST_fsm_state51 : begin
            if (((1'b1 == Bj_stream_empty_n) & (1'b1 == ap_CS_fsm_state51))) begin
                ap_NS_fsm = ap_ST_fsm_state52;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state51;
            end
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            if (((bwsup_stream_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state63))) begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state63;
            end
        end
        ap_ST_fsm_state64 : begin
            if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state64))) begin
                ap_NS_fsm = ap_ST_fsm_state65;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state64;
            end
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            if (((grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state66))) begin
                ap_NS_fsm = ap_ST_fsm_state67;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state66;
            end
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            if (((1'b0 == ap_block_state71) & (1'b1 == ap_CS_fsm_state71))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state71;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln533_fu_484_p2 = (i_2_fu_152 + 31'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state62 = ap_CS_fsm[32'd61];

assign ap_CS_fsm_state63 = ap_CS_fsm[32'd62];

assign ap_CS_fsm_state64 = ap_CS_fsm[32'd63];

assign ap_CS_fsm_state65 = ap_CS_fsm[32'd64];

assign ap_CS_fsm_state66 = ap_CS_fsm[32'd65];

assign ap_CS_fsm_state71 = ap_CS_fsm[32'd70];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state2_io = ((gmem_ARREADY == 1'b0) & (icmp_ln522_reg_589 == 1'd1));
end

always @ (*) begin
    ap_block_state33_io = ((gmem_ARREADY == 1'b0) & (icmp_ln522_reg_589 == 1'd1));
end

always @ (*) begin
    ap_block_state44 = ((icmp_ln533_fu_479_p2 == 1'd0) & (bwsup_stream_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state71 = ((gmem_BVALID == 1'b0) & (icmp_ln522_reg_589 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bitcast_ln535_fu_495_p1 = bwsup_stream_read_reg_721;

assign bitcast_ln545_fu_499_p1 = Bj_stream_read_reg_731;

assign bwsup_stream_out_din = temp_3_reg_744;

assign empty_35_fu_422_p3 = ((grp_fu_338_p2[0:0] == 1'b1) ? trunc_ln561_reg_617 : 31'd0);

assign grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_start = grp_depolarize_hls_Pipeline_computeRow_fu_293_ap_start_reg;

assign grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_start = grp_depolarize_hls_Pipeline_read_Bj_fu_284_ap_start_reg;

assign grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_start = grp_depolarize_hls_Pipeline_read_Wij_first_read_Wij_second_fu_266_ap_start_reg;

assign grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_start = grp_depolarize_hls_Pipeline_read_Xi_fu_275_ap_start_reg;

assign grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_start = grp_depolarize_hls_Pipeline_read_bwsup_fu_257_ap_start_reg;

assign grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_start = grp_depolarize_hls_Pipeline_store_bwsup_fu_303_ap_start_reg;

assign grp_fu_320_p0 = grp_fu_320_p00;

assign grp_fu_320_p00 = trunc_ln522_reg_638;

assign grp_fu_320_p1 = grp_fu_320_p10;

assign grp_fu_320_p10 = $unsigned(zext_ln482_1_fu_409_p0);

assign grp_fu_329_p4 = {{d_bwsup_read_reg_548[63:2]}};

assign grp_fu_338_p0 = Ni;

assign grp_fu_338_p2 = (($signed(grp_fu_338_p0) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign i_2_cast_fu_475_p1 = i_2_fu_152;

assign icmp_ln522_fu_355_p0 = Nj;

assign icmp_ln522_fu_355_p2 = (($signed(icmp_ln522_fu_355_p0) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln533_fu_479_p1 = Nj;

assign icmp_ln533_fu_479_p2 = ((i_2_cast_fu_475_p1 == icmp_ln533_fu_479_p1) ? 1'b1 : 1'b0);

assign select_ln485_fu_389_p3 = ((cmp2_i3763_reg_633[0:0] == 1'b1) ? mul_ln485_reg_644 : 32'd0);

assign sext_ln485_fu_395_p1 = $signed(trunc_ln2_reg_627);

assign sext_ln500_fu_429_p1 = $signed(trunc_ln3_reg_674);

assign sext_ln511_fu_452_p1 = trunc_ln4_fu_443_p4;

assign sext_ln522_fu_365_p1 = grp_fu_329_p4;

assign sext_ln554_fu_511_p1 = $signed(reg_343);

assign trunc_ln4_fu_443_p4 = {{d_Bj_read_reg_522[63:2]}};

assign trunc_ln511_fu_468_p0 = Nj;

assign trunc_ln511_fu_468_p1 = trunc_ln511_fu_468_p0[30:0];

assign trunc_ln522_fu_385_p0 = Nj;

assign trunc_ln522_fu_385_p1 = trunc_ln522_fu_385_p0[30:0];

assign trunc_ln561_fu_361_p0 = Ni;

assign trunc_ln561_fu_361_p1 = trunc_ln561_fu_361_p0[30:0];

assign zext_ln482_1_fu_409_p0 = Ni;

assign zext_ln500_fu_439_p1 = empty_35_reg_680;

endmodule //depolarize_hls
